name: Test

on:
 # repository_dispatch:
  workflow_dispatch:
    inputs:
      FEEDS_CONF:
        description: 'Feeds [必选]'
        default: 'feeds.conf.default.ufi'
      CONFIG_FILE:
        description: '调用的 [.config] 文件名称'
        default: 'mf601'
      DEFAULT_SOURCE:
        description: '源码:分支 [必选]'
        default: 'lkiuyu/openwrt-ufi:main'
  #schedule:
  #- cron: 15 10 */1  * *

env:
  DIY_P1_SH: diy-part1.sh
  DIY_P2_SH: diy-part2.sh
  UPLOAD_BIN_DIR: true
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04
    #runs-on: ubuntu-latest


    steps:
    - name: Checkout
      uses: actions/checkout@main


    - name: 环境变量设置
      run: |
        FEEDS_CONF=${{ github.event.inputs.FEEDS_CONF }}
        CONFIG_FILE=${{ github.event.inputs.CONFIG_FILE }}
        DEFAULT_SOURCE=${{ github.event.inputs.DEFAULT_SOURCE }}    
        export REPO_URL="https://github.com/$(echo $DEFAULT_SOURCE | cut -d \: -f 1)"
        export REPO_BRANCH=$(echo $DEFAULT_SOURCE | cut -d \: -f 2)
        [ -z $REPO_BRANCH ] && REPO_BRANCH=master
        echo "FEEDS_CONF=$FEEDS_CONF" >> $GITHUB_ENV
        echo "CONFIG_FILE=$CONFIG_FILE" >> $GITHUB_ENV
        echo "DEFAULT_SOURCE=$DEFAULT_SOURCE" >> $GITHUB_ENV
        echo "REPO_URL=$REPO_URL" >> $GITHUB_ENV
        echo "REPO_BRANCH=$REPO_BRANCH" >> $GITHUB_ENV

    - name: 安装依赖
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL /etc/mysql /etc/php
        sudo docker image prune --all --force
        sudo -E apt-get -qq update
        sudo apt install -y build-essential wget tar zstd
	
    - name: 缓存编译
      id: cachebuild
      uses: actions/cache@v4
      #env:
        #cache-name: cache-openwrt-lede
      with:
        path: /workdir/openwrt
        key: ${{env.DEFAULT_SOURCE}}-${{env.CONFIG_FILE}}
        restore-keys: ${{env.CONFIG_FILE}}
    
    - name: 压缩
      run: |
        tar -zcvf openwrt.tar.gz /workdir/openwrt/
        ls -lh
		
    - name: 上传 bin
      uses: actions/upload-artifact@main
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true' && !cancelled()
      with:
        name: OpenWrt_bin_${{ env.DEVICE_NAME }}_${{ env.FILE_DATE }}
        path: /workdir/openwrt.tar.gz
